
name: Build and Push

#on: [push, pull_request]
on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - '*'

env:
  IMAGE: "cocoexp"

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      run: |-
        docker build \
          --file Dockerfile \
          --tag i008/$IMAGE:$GITHUB_SHA \
          --tag i008/$IMAGE:latest \
        .

    - name: Publish
      run: |-
        docker push i008/$IMAGE:$GITHUB_SHA

    - name: PublishLatest
      if: github.ref  == 'refs/heads/master'
      run: |-
        docker push i008/$IMAGE:latest






